name: upload my image to docker hub
on:
  push:
    branches: [main]
#The Job below is running on the ubunto virtual machine.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build --tag ${{ secrets.DOCKER_USERNAME }}/${{secrets.PROJECT }}:latest .

      - name: Push Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{secrets.PROJECT }}:latest

  ## at this point the image is pushed to docker hub
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy site
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd /opt/app
            sudo docker compose pull && sudo docker compose up -d --force-recreate

## at this point we would also need to deploy to aws.

# ####
# This workflow:
# Verifies that Docker builds successfully and runs correctly.
# Sets up a Python test environment with Chromium for browser automation.
# Runs functional/UI tests using Selenium + Pytest.
# Is intended for CI validation of Dockerized Python applications with browser-based tests.
