- name: destroy final project infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - group_vars/env
    - group_vars/final-project.env
  vars:
    ansible_host_key_checking: false
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Terminate EC2 instances
      amazon.aws.ec2_instance:
        region: "{{ zone }}"
        state: terminated
        filters:
          "tag:Name": "{{ server_name }}"
          instance-state-name: ["running", "stopped", "pending", "stopping"]
        wait: yes
        wait_timeout: 300
      ignore_errors: yes

    - name: Delete Security Group
      amazon.aws.ec2_group:
        name: "{{ vpc_name }}-sg"
        region: "{{ zone }}"
        state: absent
      ignore_errors: yes

    - name: Delete Route Table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id | default('') }}"
        region: "{{ zone }}"
        route_table_id: "{{ rt_id | default('') }}"
        state: absent
      ignore_errors: yes
      when: rt_id is defined and rt_id != ""

    - name: Delete Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_id | default('') }}"
        region: "{{ zone }}"
        state: absent
      ignore_errors: yes
      when: vpc_id is defined and vpc_id != ""

    - name: Delete Subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id | default('') }}"
        region: "{{ zone }}"
        subnet_id: "{{ subnet_id | default('') }}"
        state: absent
      ignore_errors: yes
      when: subnet_id is defined and subnet_id != ""

    - name: Delete VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        vpc_id: "{{ vpc_id | default('') }}"
        region: "{{ zone }}"
        state: absent
      ignore_errors: yes
      when: vpc_id is defined and vpc_id != ""

    - name: Clean up vars file
      ansible.builtin.file:
        path: group_vars/final-project.env
        state: absent
      ignore_errors: yes

    - name: Confirmation message
      debug:
        msg: "All infrastructure has been destroyed successfully"