name: test the code upload my image to docker hub

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PROJECT: ${{ secrets.PROJECT }}
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.PROJECT }}:latest .
      - name: Run docker
        run: docker run -d --name ${{ secrets.PROJECT }} -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.PROJECT }}:latest
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.12"

      - name: Install software
        run: sudo apt-get install -y chromium-browser
      - name: install necessary packages
        run: pip install requests selenium==4.34.2 pytest webdriver-manager==4.0.2
      - name: Run the Pytest script
        run: pytest tests/ -rA
      - name: Cleanup
        if: always()
        run: |
          docker stop ${{ secrets.PROJECT }} || true
          docker rm ${{ secrets.PROJECT }} || true
